using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class DuelistNameGenerator
{
    private static readonly string[] Titles =
    {
        "Destruidor",
        "Cachaceiro",
        "Sagaz",
        "Cruel",
        "Astuto",
        "Impiedoso",
        "Ligeiro",
        "Estrategista",
        "Fedorendo",
        "Horrendo",
        "Churrasqueiro",
        "Desenrolado",
        "Tímido",
        "Ansioso",
        "Chateado",
        "Pavio Curto",
        "Pequenino",
        "Cuti-cuti",
        "Montanha",
        "Big Mike",
        "Flamenguista",
        "Rolezeiro",
        "Skatista",
        "Encanador",
        "Coveiro",
        "Teimoso",
        "Violento",
        "Amoroso",
        "Casado",
        "Solteiro",
        "Andarilho",
        "Inadimplente",
        "Caloteiro",
        "Agiota",
        "Bom Pagador",
        "Jovem Aprendiz",
        "Estagiário",
        "Repetente",
        "Adiantado",
        "Perturbado",
        "Raquitico",
        "Contador",
        "Otaku",
        "Roqueiro",
        "Pagodeiro",
        "Rei do Forró",
        "Neném da Mamãe",
        "Emancipado",
        "Ex BBB",
        "Youtuber",
        "TikToker",
        "Blogueiro",
        "Velho",
        "Missionário",
        "Carpinteiro",
        "Esbelto",
        "Magnífico",
        "Pensador",
        "Diplomata",
        "Miserável",
        "Muquirana",
        "Mão de Vaca",
        "Cabeça de Gelo",
        "Panguão",
        "Desumilde",
        "Estiloso",
        "Gamer",
        "Marombeiro",
        "Galã",
        "Cheiroso",
    };

    private static readonly string[] Names =
    {
        "Robson",
        "Vanderlei",
        "Cláudio",
        "Sérgio",
        "Jurandir",
        "Cleiton",
        "Gerson",
        "Cleidemar",
        "Clodoaldo",
        "Clóvis",
        "Teobaldo",
        "Jair",
        "Jonas",
        "Johnny",
        "Anderson",
        "Túlio",
        "Márcio",
        "Marcos",
        "Geraldo",
        "Clérison",
        "Abner",
        "Givanildo",
        "Gean",
        "Enzo",
        "Carlos",
        "Sandro",
        "Rodinei",
        "Jorge",
        "Raimundo",
        "Raul",
        "Sebastião",
        "Roberto",
        "Tarcísio",
        "Apolônio",
        "Frederico",
        "Tadeu",
        "Edson",
        "Valdemar",
        "Alcir",
        "Antônio",
        "Davidson",
        "Pablo",
        "Airton",
        "Dorival",
        "Fabrício",
        "Zé Maria",
        "Alfredo",
        "Marcelo",
        "Sidnei",
        "Francisco",
        "Éder",
        "Maicon",
        "Douglas",
        "Alex",
        "Wellinton",
    };

    public static string GenerateDuelistName()
    {
        string randomTitle = Titles[Random.Range(0, Titles.Length)];
        string randomName = Names[Random.Range(0, Names.Length)];

        return $"{randomName}, o {randomTitle}";
    }
}
